---
title       : Learn R
subtitle    : 
author      : Nehil Jain
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## What we will cover?

1. Github
2. Data Importing
3. Data Cleaning and Munging
4. Data Vizualisation 
5. Code Style Guide
6. Resources

---

## Github
1. What is source control?
2. Why Github?
3. Advantages
4. Lets do it ourselves
  - create github account
  - create a new repository
  - Go through [http://rogerdudler.github.io/git-guide/](http://rogerdudler.github.io/git-guide/)
5. [Cheatsheet](http://www.git-tower.com/blog/git-cheat-sheet/)

---


# Lets get github setup


---
## Data Importing

- Data Types in R
- Readr
- Data.Table
- Caveats
- Prevent copying data


---

# Lets do it

--- 
## Data Analysis

- plyr #later
- dplyr
- Tbl_df
- 5 verbs
  - slice
  - filter
  - select
  - arrange 
    - desc
  - mutate
  - summarise

- Grouped Operations
- Merges
  - rbind, cbind
  - left join, right join, outer join, inner join [Visual Explaination](http://www.udel.edu/evelyn/SQL-Class2/joins.jpg)
- resources

---

# Lets Do it


---

## Visualisation

- ggplot2
- ggvis
- exploratory
- Grammar of Graphics
- Some standard plot recipes
- resources
  - manhattan plot
  - correlation matrix plot
  - QQ Plots



---

# Lets Do it

---

## Code Style Guide

- Creating code vs maintaining code
- Be kind to your future self. Write readable and consistent code
- Hadley Wickam's Style Guide (http://adv-r.had.co.nz/Style.html)
- Naming is complex. Also beware of collisions
----

## Resources

- Datacamp
- Coursera
- R-bloggers
- Rdocumentation.org
- Stackoverflow





